FROM python:3.9-alpine

RUN apk update && apk upgrade && apk add postgresql-dev gcc musl-dev

WORKDIR /src

COPY requirements.txt requirements-web.txt ./
RUN pip install -r requirements.txt -r requirements-web.txt

COPY src .

CMD gunicorn --bind 0.0.0.0:$PORT web:app